### ISSUE TITLE
Occasional trajectory decoding error

### ISSUE THREAD

**Issue by arosen93** [arosen93/quacc#233]
Input:

```python
from ase.build import molecule
from jobflow.managers.local import run_locally

from quacc.recipes.tblite.core import RelaxJob

# Make an Atoms object of a water molecule
atoms = molecule('H2O')

# Make a job consisting of a GFN2-xTB relaxation calculation.
# and attach it to the Atoms object
job = RelaxJob(method='GFN2-xTB').make(atoms)

# Run the job locally
response = run_locally(job)

# Fetch the output of the job
output = response[job.uuid][1].output
```

Output:
```
Traceback (most recent call last):
  File "/home/arosen/anaconda3/envs/tutorial/lib/python3.9/site-packages/jobflow/managers/local.py", line 98, in _run_job
    response = job.run(store=store)
  File "/home/arosen/anaconda3/envs/tutorial/lib/python3.9/site-packages/jobflow/core/job.py", line 544, in run
    response = function(*self.function_args, **self.function_kwargs)
  File "/home/arosen/anaconda3/envs/tutorial/lib/python3.9/site-packages/monty/dev.py", line 113, in decorated
    return _callable(*args, **kwargs)
  File "/mnt/c/Users/asros/github/quacc/quacc/recipes/tblite/core.py", line 120, in make
    traj = run_ase_opt(
  File "/mnt/c/Users/asros/github/quacc/quacc/util/calc.py", line 225, in run_ase_opt
    traj = read(os.path.join(tmpdir, "opt.traj"), index=":")
  File "/home/arosen/anaconda3/envs/tutorial/lib/python3.9/site-packages/ase/io/formats.py", line 772, in read
    return list(_iread(filename, index, format, io, parallel=parallel,
  File "/home/arosen/anaconda3/envs/tutorial/lib/python3.9/site-packages/ase/parallel.py", line 285, in new_generator
    for result in generator(*args, **kwargs):
  File "/home/arosen/anaconda3/envs/tutorial/lib/python3.9/site-packages/ase/io/formats.py", line 842, in _iread
    for dct in io.read(fd, *args, **kwargs):
  File "/home/arosen/anaconda3/envs/tutorial/lib/python3.9/site-packages/ase/io/trajectory.py", line 408, in read_traj
    yield trj[i]
  File "/home/arosen/anaconda3/envs/tutorial/lib/python3.9/site-packages/ase/io/trajectory.py", line 261, in __getitem__
    b = self.backend[i]
  File "/home/arosen/anaconda3/envs/tutorial/lib/python3.9/site-packages/ase/io/ulm.py", line 583, in __getitem__
    data = self._read_data(index)
  File "/home/arosen/anaconda3/envs/tutorial/lib/python3.9/site-packages/ase/io/ulm.py", line 577, in _read_data
    data = decode(self._fd.read(size).decode(), False)
ValueError: read length must be non-negative or -1
```

Rerunning it fixes it, so it might be a caching issue. I have also only seen this happen from within a Jupyter Notebook.

**Comment by arosen93** [comment]
Not able to reproduce.
